CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions CASCADE;
CREATE EXTENSION IF NOT EXISTS tsm_system_rows WITH SCHEMA extensions CASCADE;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions CASCADE;
