CREATE EXTENSION pg_cron WITH SCHEMA extensions CASCADE;
CREATE EXTENSION pg_jsonschema WITH SCHEMA extensions CASCADE;
CREATE EXTENSION pg_net WITH SCHEMA extensions CASCADE;
CREATE EXTENSION tsm_system_rows WITH SCHEMA extensions CASCADE;
CREATE EXTENSION vector WITH SCHEMA extensions CASCADE;
