name: Cron Job
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Call scrape API
        run: curl -X POST https://iwallpaper.onrender.com/scrape/cron
